title: <p align="center">Rakesh Rajan</p>
logo: /assets/img/logo.png
description: 
<p align="center">
<a href="https://www.linkedin.com/in/rakesh-rajan-11846a60/">Linkedin</a>
<a href="https://github.com/rrajanml">GitHub</a>
<br>
I am starting my career in Machine Learning, AI related Technologies/
I am really passionate to learn, implement in real world scenarios.
<br>
</p>
theme: jekyll-theme-minimal
